### ISSUE TITLE
Python 3.8 dependent topology

### ISSUE THREAD

**Issue by mateibarbu19** [alexmircea98/temaEP#1]
Why did you take the decision to remove the topology source code in the last moment [commit](https://github.com/alexmircea98/temaEP/commit/c4b60fcb7c78d5ac46e4efb4ba903a89b8640595)?
Not only is this approach Python 3.8 dependent, but also posts only the compiled program onto a open-source platform.

**Comment by alexmircea98** [comment]
It was a last minute decision taken by the team  in a meeting, to "try to hide" the modifiers on links and make them less obvious.  It was decided that the challenge should be to make the evaluation by measurements with the right tools, not by looking at the config. 

As the recommended VM with the environment came with python 3.8 I did not see it as such a big issue. I intend to publish the source code after the assignment deadline. Although, there are several methods at the moment to discover the source code.

**Comment by mateibarbu19** [comment]
> It was a last minute decision taken by the team in a meeting, to "try to hide" the modifiers on links and make them less obvious. It was decided that the challenge should be to make the evaluation by measurements with the right tools, not by looking at the config.
> 
> As the recommended VM with the environment came with python 3.8 I did not see it as such a big issue. I intend to publish the source code after the assignment deadline. Although, there are several methods at the moment to discover the source code.

This makes sense. I think a good idea is to mention that simply taking the answer for granted from the source will not be accepted. Thanks for your help!
